import requests
from requests.compat import urljoin
from ..client import CxOneClient


async def generate_upload_link(client : CxOneClient) -> requests.Response:
    """|LowLevelApiDocstring|"""
    url = urljoin(client.api_endpoint, "uploads")
    return await client.exec_request(requests.post, url)

async def upload_to_link(client : CxOneClient, upload_link : str,
                         local_zip_path : str) -> requests.Response:
    """
    A method to upload a zip file to an upload link generated by the REST API

    Parameters:

    client - An instance of CxOneClient.
    upload_link - The link URL generated by the REST API
    local_zip_path - A path to a local zip file to be uploaded.
    
    """
    upload_response = None

    with open(local_zip_path, "rb") as zip_to_upload:
        upload_response = await client.exec_request(requests.put, upload_link, data=zip_to_upload)

    return upload_response
