name: Build API Docs [called]
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ''
      buildonly:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build-api-docs:
    runs-on: cx-public-ubuntu-x64
    container: sphinxdoc/sphinx-latexpdf:8.2.3@sha256:0fc72dace4e1b181721c8ccacfa7835d6824cb1619ba060f3940e4ac73bd911c
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ inputs.version }}

      - name: Build PDF
        run: |
          echo "__version__='${{ inputs.version }}'" > cxone_api/__version__.py
          pip install sphinx-autoapi .
          PYTHONPATH=$(pwd) sphinx-build -M latexpdf -c docs . docs_build && : || :
          make -C docs_build
          mv docs_build/cxone-async-api.pdf docs_build/cxone-async-api-${{ inputs.version }}.pdf

      - name: Upload apidoc pdf artifact
        if: ${{ ! inputs.buildonly }}
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: apidoc-pdf-${{ github.run_number }}
          path: docs_build/*.pdf          
