name: CI Build Steps [called]
on:
  push:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  call-unit-tests-coverage:
    needs: [call-build-api-docs, call-build-package]
    uses: ./.github/workflows/coverage.yml
    secrets:
      TEST_TENANT_ID: ${{ vars.TEST_TENANT_ID }}
      TEST_REGION: ${{ vars.TEST_REGION }}
      TEST_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_OAUTH_CLIENT_SECRET }}
      TEST_OAUTH_CLIENT_ID: ${{ secrets.TEST_OAUTH_CLIENT_ID }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

  execute-pylint:
    runs-on: cx-public-ubuntu-x64
    strategy:
      max-parallel: 3
      matrix:
        pver:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '${{ matrix.pver }}'

      - name: Install packages
        shell: bash
        run: |
          pip config set global.index-url https://pypi.echohq.com/simple
          pip install . pylint

      - name: Pylint
        shell: bash
        run: |
          pylint --disable=all --enable=E,F --disable=E1121 --score=false cxone_api

  call-build-api-docs:
    uses: ./.github/workflows/build-api-docs.yml
    with:
      buildonly: true

  call-build-package:
    uses: ./.github/workflows/build-wheel.yml
    with:
      buildonly: true
