name: CI Build
on:
    workflow_call:
    workflow_dispatch:
    push:

jobs:

    call-unit-tests-coverage:
        uses: ./.github/workflows/coverage.yml
        secrets:
          TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
          TEST_REGION: ${{ secrets.TEST_REGION }}
          TEST_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_OAUTH_CLIENT_SECRET }}
          TEST_OAUTH_CLIENT_ID: ${{ secrets.TEST_OAUTH_CLIENT_ID }}
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

    