name: Unit Tests and Coverage Steps [called]
on:
  workflow_call:
    secrets:
      TEST_TENANT_ID:
        required: true
      TEST_REGION:
        required: true
      TEST_OAUTH_CLIENT_SECRET:
        required: true
      TEST_OAUTH_CLIENT_ID:
        required: true
      TEST_API_KEY:
        required: true
    inputs:
      skip:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  skip-unit-tests-coverage:
    runs-on: cx-public-ubuntu-x64
    if: ${{ inputs.skip }}
    steps:
      - name: Dummy
        run: exit 0
      

  execute-unit-tests-coverage:
    runs-on: cx-public-ubuntu-x64
    if: ${{ ! inputs.skip }}
    env:
      TEST_TENANT_ID: ${{ vars.TEST_TENANT_ID }}
      TEST_REGION: ${{ vars.TEST_REGION }}
      TEST_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_OAUTH_CLIENT_SECRET }}
      TEST_OAUTH_CLIENT_ID: ${{ secrets.TEST_OAUTH_CLIENT_ID }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - name: Install build packages
        run: pip install coverage build python-dotenv

      - name: Execute Unit Tests
        run: |
          export PYTHONPATH=$(pwd)
          echo "__version__='0.0.0'" > cxone_api/__version__.py
          python3 -m build
          pip3 install -r ./cxone_api.egg-info/requires.txt
          coverage run -m unittest -f -v
          coverage report
