name: Unit Tests and Coverage
on:
    workflow_call:

jobs:
     execute-unit-tests-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch Code
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
            
            - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
              with:
                python-version: '3.12'

            - name: Install packages
              run: pip install coverage

            - name: Execute Unit Tests
              run: |
                coverage run -m unittest -f -v
                coverage report
    