name: Publish a Release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version tag to use in the form of x.x.x'
        required: true
        type: string
      prerelease:
        description: 'Check if this is to publish a pre-release.'
        required: true
        type: boolean


jobs:
  make-tag-string:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
    steps:
      - name: Create tag
        run: |
          [ ${{ inputs.prerelease }} = false ] && echo "tag=v${{ inputs.version }}" >> $GITHUB_OUTPUT || \
            echo "tag=v${{ inputs.version }}-$GITHUB_RUN_NUMBER-prerelease" >> $GITHUB_OUTPUT
        id: tag-string
      
  validate-no-tag:
    runs-on: ubuntu-latest
    needs: [make-tag-string]
    steps:
      - name: Fetch Code
        continue-on-error: true
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          ref: refs/tags/${{ needs.make-tag-string.outputs.tag }}
      - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} exists
        run: |
          [[ $(git describe --tags) ==  ${{ needs.make-tag-string.outputs.tag }} ]] && exit 1 || :


  create-tag:
    runs-on: ubuntu-latest
    needs: [validate-no-tag]
    steps:
      - name: Tag repo ${{ needs.make-tag-string.outputs.tag }}
        uses: richardsimko/update-tag@e173a8ef8f54ab526a91dad6139a25efed62424c
        with:
          tag_name: ${{ needs.make-tag-string.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
  publish-release:
    needs: [create-tag]
    runs-on: ubuntu-latest
    steps:
        - name: FAIL
          run: |
            sleep 60
            exit 1



  remove-tag-on-failure:
    needs: [create-tag, publish-release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5
      - name: Fetch Code
        uses: actions/checkout@v3
        if: env.WORKFLOW_CONCLUSION == 'failure'

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ inputs.tag }}'
        if: env.WORKFLOW_CONCLUSION == 'failure'