name: Publish a Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version tag to use in the form of x.x.x"
        required: true
        type: string
      prerelease:
        description: "Check if this is to publish a pre-release."
        required: true
        type: boolean
      skiputs:
        description: "Check to skip unit test execution (not advised)."
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  make-tag-string:
    if: ${{ inputs.version != '' }}
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag: ${{ steps.tag-string.outputs.tag }}
      release_version: ${{ steps.tag-string.outputs.release_version }}
    steps:
      - name: Create tag string
        run: |
          [ ${{ inputs.prerelease }} = false ] && echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT || \
            echo "tag=${{ inputs.version }}rc$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

          echo "release_version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        id: tag-string

  validate-no-tag:
    if: ${{ inputs.version != '' }}
    runs-on: cx-public-ubuntu-x64
    needs: [make-tag-string]
    steps:
      - name: Fetch Code
        continue-on-error: true
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: refs/tags/${{ needs.make-tag-string.outputs.tag }}

      - name: Fail if tag ${{ needs.make-tag-string.outputs.tag }} exists
        run: |
          [[ $(git describe --tags) ==  ${{ needs.make-tag-string.outputs.tag }} ]] && exit 1 || :

  call-unit-tests-coverage:
    uses: ./.github/workflows/coverage.yml
    needs: [create-tag]
    with:
      skip: ${{ inputs.skiputs }}
      version: ${{ inputs.version }}
    secrets:
      TEST_TENANT_ID: ${{ vars.TEST_TENANT_ID }}
      TEST_REGION: ${{ vars.TEST_REGION }}
      TEST_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_OAUTH_CLIENT_SECRET }}
      TEST_OAUTH_CLIENT_ID: ${{ secrets.TEST_OAUTH_CLIENT_ID }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}


  build-api-docs:
    uses: ./.github/workflows/build-api-docs.yml
    needs: [create-tag, make-tag-string]
    with:
      version: ${{ needs.make-tag-string.outputs.tag }}

  build-package:
    uses: ./.github/workflows/build-wheel.yml
    needs: [create-tag, make-tag-string]
    with:
      version: ${{ needs.make-tag-string.outputs.tag }}

  create-tag:
    permissions:
      contents: write
    if: ${{ inputs.version != '' }}
    runs-on: cx-public-ubuntu-x64
    needs: [make-tag-string, validate-no-tag]
    outputs:
      done: ${{ steps.done_check.outputs.status }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        
      - name: Set Version
        run: |
          git config --global user.email "${{ github.triggering_actor }}"
          git config --global user.name "${{ github.triggering_actor }}"
          git tag ${{ needs.make-tag-string.outputs.tag }}
          git push origin --tags

      - name: Set tag status
        id: done_check
        run: |
          echo "status=true" >> "$GITHUB_OUTPUT"

  publish-release:
    permissions:
      contents: write
    runs-on: cx-public-ubuntu-x64
    needs: [build-package, build-api-docs, call-unit-tests-coverage]
    steps:
      - name: Download apidoc pdf artifact
        if: ${{ ! inputs.buildonly }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: apidoc-pdf-${{ github.run_number }}

      - name: Download wheel artifact
        if: ${{ ! inputs.buildonly }}
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: wheel-${{ github.run_number }}

      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          refs: ${{ needs.make-tag-string.outputs.tag }}

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - name: Make release text
        run: |
          echo "# Checkmarx One Async API ${{ inputs.version }}" > release.md

          python3 ./.github/workflows/scripts/json2md.py ./release-notes.json ${{ needs.make-tag-string.outputs.release_version }} >> release.md

          echo '\n\n## Installation' >> release.md
          echo 'Installation can be performed by adding one of the following lines to your `requirements.txt` file:' >> release.md
          WHEEL_NAME=$(basename $(ls *.whl))
          WHEEL_HASH=$(pip hash $WHEEL_NAME | grep "^--")
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${{ inputs.version }}/$WHEEL_NAME"

          echo '```' >> release.md
          echo $RELEASE_URL >> release.md
          echo '```' >> release.md

          echo '```' >> release.md
          echo "git+https://github.com/${{ github.repository }}.git@${{ inputs.version }}" >> release.md
          echo '```' >> release.md

          echo "## Hashes" >> release.md
          echo "### $WHEEL_NAME" >> release.md
          echo '```' >> release.md
          echo "$WHEEL_HASH" >> release.md
          echo '```' >> release.md


      - name: Create GitHub release
        id: create_release
        uses: step-security/release-action@a0d8e0f90f554c15366ca2c9046bf4090d24adbe # v1.21.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "*.whl,*.pdf"
          bodyFile: release.md
          name: ${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}
          tag: ${{ inputs.version }}

  artifact-cleanup:
    runs-on: cx-public-ubuntu-x64
    needs: [publish-release]
    steps:
      - uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118
        with:
          name: |
            apidoc-pdf-${{ github.run_number }}
            wheel-${{ github.run_number }}

  remove-tag-on-failure:
    needs: [create-tag, publish-release, make-tag-string]
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: write
    if: ${{ failure() && needs.create-tag.outputs.done }}
    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Remove CodeTag
        run: git push origin ':refs/tags/${{ needs.make-tag-string.outputs.tag }}'
